#!/usr/bin/env python3
"""Generate navigation/evidence indexes and check corpus-free repository freshness."""
from __future__ import annotations

import argparse
import ast
import hashlib
import json
import re
import subprocess
from pathlib import Path
from urllib.parse import unquote, urlsplit

from evidence_common import Invalid
from progress_report import outputs as progress_outputs
from recorded_decisions import read_decisions

ROOT = Path(__file__).resolve().parent.parent
GENERATED = ('tools/README.md', 'docs/README.md', 'notes/evidence/INDEX.md',
             'notes/evidence/index.json', 'progress/report.json', 'progress/provenance.json')


def tracked(root: Path) -> list[str]:
    output = subprocess.check_output(['git', '-C', str(root), 'ls-files', '-z'])
    return sorted(set(x.decode() for x in output.split(b'\0') if x))


def description(path: Path) -> str:
    if path.suffix == '.py':
        try:
            doc = ast.get_docstring(ast.parse(path.read_text())) or 'Python module; see source.'
        except (SyntaxError, UnicodeError):
            doc = 'Python source; see file.'
        prefix = 'Tests: ' if path.name.startswith('test_') else ''
        return prefix + doc.strip().splitlines()[0]
    text = path.read_text()
    heading = re.search(r'^#+\s+(.+)$', text, re.M)
    return heading.group(1) if heading else 'Documentation; see file.'


def index(title: str, files: list[str], base: Path, root: Path) -> str:
    import os
    rows = [f'# {title}', '', 'Generated by `python3 tools/repository_hygiene.py generate`.', '',
            'Each entry links to its source. Test modules are marked explicitly.', '']
    for name in files:
        relative = Path(os.path.relpath(root / name, base)).as_posix()
        summary = description(root / name).replace('\n', ' ').replace('`', '')
        rows.append(f'- [{name}]({relative}) — {summary}')
    return '\n'.join(rows) + '\n'


def evidence_entry(name: str, root: Path) -> dict:
    text = (root / name).read_text()
    commands = []
    for language, block in re.findall(r'^```([^\n]*)\n(.*?)^```', text, re.M | re.S):
        if language.strip() in ('sh', 'bash', 'shell', 'console') or re.search(r'^(?:python\S* |tools/)', block, re.M):
            commands.append(block.rstrip())
    sha256_mentions, revision_mentions = [], []
    for number, line in enumerate(text.splitlines(), 1):
        for match in re.finditer(r'(?<![0-9a-f])[0-9a-f]{64}(?![0-9a-f])', line, re.I):
            sha256_mentions.append({'value': match.group(), 'line': number, 'context': line})
        for match in re.finditer(r'(?<![0-9a-f])[0-9a-f]{40}(?![0-9a-f])', line, re.I):
            revision_mentions.append({'value': match.group(), 'line': number, 'context': line})
    missing = []
    if not commands:
        missing.append('reproduction_command')
    if not sha256_mentions:
        missing.append('full_sha256_mention')
    if not revision_mentions:
        missing.append('full_revision_mention')
    return {'path': name, 'readme_sha256': hashlib.sha256(text.encode()).hexdigest(),
            'commands': commands, 'sha256_mentions': sha256_mentions,
            'revision_mentions': revision_mentions, 'missing': missing}


def generated_outputs(root: Path = ROOT) -> dict[str, str]:
    files = tracked(root)
    tool_files = [x for x in files if x.startswith('tools/') and x.endswith('.py')]
    doc_files = [x for x in files if x.startswith('docs/') and x.endswith('.md') and x not in GENERATED]
    entries = [evidence_entry(x, root) for x in files
               if x.startswith('notes/evidence/') and x.endswith('/README.md')]
    evidence = {'schema': 'fr2-evidence-index/v1',
                'limits': ['Pins are verbatim mentions with source line/context, not semantic assignments.',
                           'Missing fields are unresolved; commands are indexed, never executed.',
                           'An indexed README is not independent verification of its measurements.'],
                'entries': entries}
    rows = ['# Evidence index', '', 'Generated by `python3 tools/repository_hygiene.py generate`.', '',
            'Commands and full hash/revision mentions are copied with their source context in',
            '[index.json](index.json). Missing fields are recorded rather than inferred.', '']
    for entry in entries:
        name = entry['path'].removeprefix('notes/evidence/')
        missing = ', '.join(entry['missing']) or 'none'
        rows.append(f"- [{name}]({name}) — {len(entry['commands'])} command blocks; missing: {missing}.")
    return {'tools/README.md': index('Tools index', tool_files, root / 'tools', root),
            'docs/README.md': index('Documentation index', doc_files, root / 'docs', root),
            'notes/evidence/INDEX.md': '\n'.join(rows) + '\n',
            'notes/evidence/index.json': json.dumps(evidence, indent=2) + '\n',
            **progress_outputs(root)}


def validate_schema(value, schema: dict, document: dict, location: str = '$') -> None:
    """Evaluate the keywords used by the vendored recomp v1 schema; fail on unknown ones."""
    supported = {'$schema', '$id', '$defs', '$ref', 'title', 'description', 'examples',
                 'type', 'enum', 'oneOf', 'properties', 'patternProperties',
                 'additionalProperties', 'required', 'minProperties', 'minLength',
                 'pattern', 'items', 'minItems', 'uniqueItems'}
    if set(schema) - supported:
        raise Invalid('unsupported schema keywords: ' + str(set(schema) - supported))
    if '$ref' in schema:
        reference = schema['$ref']
        if not reference.startswith('#/$defs/'):
            raise Invalid('only local schema definitions are supported')
        validate_schema(value, document['$defs'][reference.split('/')[-1]], document, location)
    if 'oneOf' in schema:
        matches = 0
        for choice in schema['oneOf']:
            try:
                validate_schema(value, choice, document, location)
                matches += 1
            except Invalid:
                pass
        if matches != 1:
            raise Invalid(location + ': must match exactly one schema alternative')
    expected = schema.get('type')
    kinds = {'object': dict, 'array': list, 'string': str}
    if expected and type(value) is not kinds[expected]:
        raise Invalid(location + ': wrong type, expected ' + expected)
    if 'enum' in schema and value not in schema['enum']:
        raise Invalid(location + ': unsupported value')
    if isinstance(value, dict):
        if len(value) < schema.get('minProperties', 0):
            raise Invalid(location + ': empty object')
        if set(schema.get('required', [])) - set(value):
            raise Invalid(location + ': required properties missing')
        for name, item in value.items():
            prop = schema.get('properties', {}).get(name)
            patterns = [s for p, s in schema.get('patternProperties', {}).items() if re.search(p, name)]
            if prop is not None:
                validate_schema(item, prop, document, location + '.' + name)
            for pattern in patterns:
                validate_schema(item, pattern, document, location + '.' + name)
            if prop is None and not patterns and schema.get('additionalProperties') is False:
                raise Invalid(location + ': unknown property ' + name)
    if isinstance(value, list):
        if len(value) < schema.get('minItems', 0):
            raise Invalid(location + ': empty array')
        if schema.get('uniqueItems') and len({json.dumps(v, sort_keys=True) for v in value}) != len(value):
            raise Invalid(location + ': duplicate array items')
        for number, item in enumerate(value):
            if 'items' in schema:
                validate_schema(item, schema['items'], document, f'{location}[{number}]')
    if isinstance(value, str):
        if len(value) < schema.get('minLength', 0):
            raise Invalid(location + ': empty string')
        if 'pattern' in schema and not re.search(schema['pattern'], value):
            raise Invalid(location + ': pattern mismatch')


def broken_links(root: Path, files: list[str]) -> list[str]:
    broken = []
    for name in files:
        if not name.endswith('.md'):
            continue
        text = (root / name).read_text()
        text = re.sub(r'^```.*?^```[^\n]*', '', text, flags=re.M | re.S)
        text = re.sub(r'`[^`\n]*`', '', text)
        targets = re.findall(r'!?\[[^\]]*\]\(([^\n)]+)\)', text)
        targets += re.findall(r'^\[[^\]]+\]:\s*(\S+)', text, re.M)
        for target in targets:
            target = target.strip().split(' "', 1)[0].strip('<>')
            if target.startswith('#') or urlsplit(target).scheme or target.startswith('/'):
                continue
            path = unquote(target.split('#', 1)[0])
            if not path:
                continue
            destination = (root / name).parent / path
            # External local evidence is outside this repository's portable check.
            if not destination.resolve().is_relative_to(root.resolve()):
                continue
            if not destination.exists():
                broken.append(name + ': ' + target)
    return broken


def check(root: Path = ROOT) -> list[str]:
    read_decisions(root)
    schema = json.loads((root / 'tools/schemas/recomp-v1.json').read_text())
    metadata = json.loads((root / '.recomp.json').read_text())
    validate_schema(metadata, schema, schema)
    if metadata.get('status') in ('complete', 'playable', 'released'):
        raise Invalid('discovery status exceeds the established reconstruction')
    errors = []
    for name, expected in generated_outputs(root).items():
        path = root / name
        if not path.is_file() or path.read_text() != expected:
            errors.append('generated file is missing or stale: ' + name)
    errors.extend('broken repository link: ' + x for x in broken_links(root, tracked(root)))
    return errors


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('mode', choices=('generate', 'check'))
    args = parser.parse_args()
    try:
        if args.mode == 'generate':
            for name, text in generated_outputs().items():
                path = ROOT / name
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(text)
            print('Generated tool/docs/evidence indexes and structural progress report')
            return 0
        errors = check()
    except (Invalid, OSError, ValueError, KeyError) as error:
        errors = [str(error)]
    for error in errors:
        print(error)
    if not errors:
        print('PASS: decision/evidence bindings, schema, indexes, links, zero-credit report freshness')
    return 1 if errors else 0


if __name__ == '__main__':
    raise SystemExit(main())
